# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStastics',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.SmallIntegerField()),
                ('cost', models.FloatField()),
                ('day', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'daily_stastics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.SmallIntegerField()),
                ('time', models.IntegerField()),
                ('cost', models.FloatField()),
                ('pri_type', models.SmallIntegerField()),
                ('sec_type', models.SmallIntegerField()),
                ('period', models.SmallIntegerField()),
                ('cost_name', models.CharField(max_length=256)),
                ('seller', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('mon', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodTbl',
            fields=[
                ('value', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'period_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriTypeTbl',
            fields=[
                ('value', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'pri_type_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecTypeTbl',
            fields=[
                ('value', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('pri_type', models.SmallIntegerField()),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sec_type_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
